<a href="https://colab.research.google.com/github/DrShabirAhmad/Code/blob/main/Combinatorics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
survey1 = [35, 36, 33,32, 34, 35] # amazon sde2 salaries
survey2 = [20, 37, 50, 90, 25, 35] # MSFT sde2 salaries

In [ ]:
np.mean(survey1)

34.166666666666664

In [ ]:
np.mean(survey2)

52.833333333333336

In [ ]:
np.random.choice(survey1, size=6)

array([32, 35, 35, 34, 36, 34])

In [ ]:
np.random.choice(survey1, size=6)

array([35, 36, 32, 36, 35, 34])

In [ ]:
np.random.choice(survey1, size=6)

array([33, 32, 33, 34, 32, 35])

In [ ]:
# Step 1
# randomly take samples (n = 6)
boostrapped_sample = np.random.choice(survey1, size=6)
np.median(boostrapped_sample)

34.0

In [ ]:
boostrapped_sample = np.random.choice(survey1, size=6)
np.median(boostrapped_sample)

35.0

In [ ]:
boostrapped_sample = np.random.choice(survey1, size=6)
np.median(boostrapped_sample)

34.0

In [ ]:
sample_medians = []
for _ in range(1000):
    bootsrapped_samples = np.random.choice(survey1, size=6)
    bootsrapped_samples_median = np.median(bootsrapped_samples)
    sample_medians.append(bootsrapped_samples_median)

In [ ]:
sample_medians[:15]

[35.0,
 34.5,
 34.0,
 34.5,
 35.0,
 33.0,
 33.0,
 34.5,
 35.0,
 36.0,
 35.0,
 34.0,
 35.0,
 34.0,
 35.0]

In [ ]:
sample_medians = np.sort(sample_medians)

In [ ]:
sample_medians[:15]

array([32. , 32. , 32. , 32. , 32.5, 32.5, 32.5, 32.5, 32.5, 32.5, 32.5,
       32.5, 32.5, 32.5, 32.5])

In [ ]:
sample_medians[-15:]

array([35.5, 35.5, 35.5, 35.5, 35.5, 35.5, 36. , 36. , 36. , 36. , 36. ,
       36. , 36. , 36. , 36. ])

In [ ]:
sample_medians[25], sample_medians[975]

(32.5, 35.5)

In [ ]:
np.percentile(sample_medians, 2.5)

32.5

In [ ]:
np.percentile(sample_medians, 97.5)

35.5

In [ ]:
# sns.histplot(sample_medians)