<a href="https://colab.research.google.com/github/DrShabirAhmad/Code/blob/main/Proof_of_Theorem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [ ]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
print("Mohtashim, Muqsit, Muwahid, Samia Jan, Dr. Shabir Ahmad "*5, end='\n')

Mohtashim, Muqsit, Muwahid, Samia Jan, Dr. Shabir Ahmad Mohtashim, Muqsit, Muwahid, Samia Jan, Dr. Shabir Ahmad Mohtashim, Muqsit, Muwahid, Samia Jan, Dr. Shabir Ahmad Mohtashim, Muqsit, Muwahid, Samia Jan, Dr. Shabir Ahmad Mohtashim, Muqsit, Muwahid, Samia Jan, Dr. Shabir Ahmad 


In [ ]:
np.arange(1,101).reshape(20,5)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [ ]:
print('I Love You Muqsit & Mohtashim')

I Love You Muqsit & Mohtashim


In [ ]:
a= 'shabir'
print(a[::-1])

ribahs


In [ ]:
d = {'apple': 'red', 'banana': 'yellow', 'cherry': 'green', 'date': 'brown'}


def reverse_dict_no_duplicates(d):

    output = {}

    for elem in d.items():
        k, v = elem #unpacking
        output[v] = k[::-1]

    return output

In [ ]:
reverse_dict_no_duplicates({'apple': 'red', 'banana': 'yellow', 'cherry': 'green', 'date': 'brown'})

{'red': 'elppa', 'yellow': 'ananab', 'green': 'yrrehc', 'brown': 'etad'}

In [ ]:
mat = np.arange(1,17).reshape(4,4)

In [ ]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
def DiagonalSums(mat):
  principal_diagonal_sum = 0
  secondary_diagonal_sum = 0

  n= len(mat)

  for i in range(n):
    principal_diagonal_sum += mat[i][i]
    secondary_diagonal_sum += mat[i][n-1-i]     # i+j = n-1

  print("Principal Diagonal:", principal_diagonal_sum)
  print("Seconadary Diagonal:", secondary_diagonal_sum)

In [ ]:
mat = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12],
       [13, 14, 15, 16]]

In [ ]:
mat= np.arange(5, 54).reshape(7,7)
mat

array([[ 5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46],
       [47, 48, 49, 50, 51, 52, 53]])

In [ ]:
mat = np.arange(0, 36).reshape(6,6)
mat

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
mat = np.arange(0, 2500).reshape(50,50)
mat

array([[   0,    1,    2, ...,   47,   48,   49],
       [  50,   51,   52, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  147,  148,  149],
       ...,
       [2350, 2351, 2352, ..., 2397, 2398, 2399],
       [2400, 2401, 2402, ..., 2447, 2448, 2449],
       [2450, 2451, 2452, ..., 2497, 2498, 2499]])

In [ ]:
DiagonalSums(mat)

Principal Diagonal: 62475
Seconadary Diagonal: 62475


In [ ]:
Square_matrix= np.arange(0,9).reshape(3,3)
Square_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
def DiagonalSums(Square_matrix):
  principal_diagonal_sum = 0
  secondary_diagonal_sum = 0

  n= len(mat)

  for i in range(n):
    principal_diagonal_sum += mat[i][i]
    secondary_diagonal_sum += mat[i][n-1-i]     # i+j = n-1

  print("Principal Diagonal:", principal_diagonal_sum)
  print("Seconadary Diagonal:", secondary_diagonal_sum)

In [ ]:
len(Square_matrix)

3