<a href="https://colab.research.google.com/github/DrShabirAhmad/Code/blob/main/SumofDiagonalsofSquare_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
Square_matrix= np.arange(0,9).reshape(3,3)
Square_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
def DiagonalSums(Square_matrix):
  principal_diagonal_sum = 0
  secondary_diagonal_sum = 0

  n= len(Square_matrix)

  for i in range(n):
    principal_diagonal_sum += Square_matrix[i][i]
    secondary_diagonal_sum += Square_matrix[i][n-1-i]     # i+j = n-1

  print("Principal Diagonal:", principal_diagonal_sum)
  print("Secondary Diagonal:", secondary_diagonal_sum)

In [9]:
DiagonalSums(Square_matrix)

Principal Diagonal: 12
Secondary Diagonal: 12


In [10]:
Square_matrix = np.arange(0, 2500).reshape(50,50)      # Whole numbers
Square_matrix

array([[   0,    1,    2, ...,   47,   48,   49],
       [  50,   51,   52, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  147,  148,  149],
       ...,
       [2350, 2351, 2352, ..., 2397, 2398, 2399],
       [2400, 2401, 2402, ..., 2447, 2448, 2449],
       [2450, 2451, 2452, ..., 2497, 2498, 2499]])

In [11]:
DiagonalSums(Square_matrix)

Principal Diagonal: 62475
Secondary Diagonal: 62475


In [18]:
Square_matrix = np.arange(5, 54).reshape(7,7)      # Natural numbers
Square_matrix

array([[ 5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46],
       [47, 48, 49, 50, 51, 52, 53]])

In [19]:
DiagonalSums(Square_matrix)

Principal Diagonal: 203
Secondary Diagonal: 203


In [16]:
Square_matrix = np.arange(1, 4901).reshape(70,70)      # Natural numbers
Square_matrix

array([[   1,    2,    3, ...,   68,   69,   70],
       [  71,   72,   73, ...,  138,  139,  140],
       [ 141,  142,  143, ...,  208,  209,  210],
       ...,
       [4691, 4692, 4693, ..., 4758, 4759, 4760],
       [4761, 4762, 4763, ..., 4828, 4829, 4830],
       [4831, 4832, 4833, ..., 4898, 4899, 4900]])

In [17]:
DiagonalSums(Square_matrix)

Principal Diagonal: 171535
Secondary Diagonal: 171535


In [20]:
Square_matrix = np.arange(500, 598, 2).reshape(7,7)
Square_matrix

array([[500, 502, 504, 506, 508, 510, 512],
       [514, 516, 518, 520, 522, 524, 526],
       [528, 530, 532, 534, 536, 538, 540],
       [542, 544, 546, 548, 550, 552, 554],
       [556, 558, 560, 562, 564, 566, 568],
       [570, 572, 574, 576, 578, 580, 582],
       [584, 586, 588, 590, 592, 594, 596]])

In [21]:
DiagonalSums(Square_matrix)

Principal Diagonal: 3836
Secondary Diagonal: 3836


In [24]:
Square_matrix = np.arange(500, 10500, 100).reshape(10,10)
Square_matrix

array([[  500,   600,   700,   800,   900,  1000,  1100,  1200,  1300,
         1400],
       [ 1500,  1600,  1700,  1800,  1900,  2000,  2100,  2200,  2300,
         2400],
       [ 2500,  2600,  2700,  2800,  2900,  3000,  3100,  3200,  3300,
         3400],
       [ 3500,  3600,  3700,  3800,  3900,  4000,  4100,  4200,  4300,
         4400],
       [ 4500,  4600,  4700,  4800,  4900,  5000,  5100,  5200,  5300,
         5400],
       [ 5500,  5600,  5700,  5800,  5900,  6000,  6100,  6200,  6300,
         6400],
       [ 6500,  6600,  6700,  6800,  6900,  7000,  7100,  7200,  7300,
         7400],
       [ 7500,  7600,  7700,  7800,  7900,  8000,  8100,  8200,  8300,
         8400],
       [ 8500,  8600,  8700,  8800,  8900,  9000,  9100,  9200,  9300,
         9400],
       [ 9500,  9600,  9700,  9800,  9900, 10000, 10100, 10200, 10300,
        10400]])

In [25]:
DiagonalSums(Square_matrix)

Principal Diagonal: 54500
Secondary Diagonal: 54500


In [29]:
Square_matrix = np.arange(500, 1065, 7).reshape(9,9)
Square_matrix

array([[ 500,  507,  514,  521,  528,  535,  542,  549,  556],
       [ 563,  570,  577,  584,  591,  598,  605,  612,  619],
       [ 626,  633,  640,  647,  654,  661,  668,  675,  682],
       [ 689,  696,  703,  710,  717,  724,  731,  738,  745],
       [ 752,  759,  766,  773,  780,  787,  794,  801,  808],
       [ 815,  822,  829,  836,  843,  850,  857,  864,  871],
       [ 878,  885,  892,  899,  906,  913,  920,  927,  934],
       [ 941,  948,  955,  962,  969,  976,  983,  990,  997],
       [1004, 1011, 1018, 1025, 1032, 1039, 1046, 1053, 1060]])

In [30]:
DiagonalSums(Square_matrix)

Principal Diagonal: 7020
Secondary Diagonal: 7020


In [33]:
Square_matrix = np.arange(0, 106, 3).reshape(6,6)
Square_matrix

array([[  0,   3,   6,   9,  12,  15],
       [ 18,  21,  24,  27,  30,  33],
       [ 36,  39,  42,  45,  48,  51],
       [ 54,  57,  60,  63,  66,  69],
       [ 72,  75,  78,  81,  84,  87],
       [ 90,  93,  96,  99, 102, 105]])

In [34]:
DiagonalSums(Square_matrix)

Principal Diagonal: 315
Secondary Diagonal: 315
